use anyhow::Result;
use toml::Value;

use crate::resolve::ResolvedTheme;

pub fn emit_theme_toml(
    name: &str,
    version: u64,
    base_light: &Value,
    base_dark: &Value,
    resolved: &ResolvedTheme,
) -> Result<String> {
    let mut light = base_light.clone();
    let mut dark = base_dark.clone();
    crate::resolve::apply_resolved_mode(&mut light, &resolved.light)?;
    crate::resolve::apply_resolved_mode(&mut dark, &resolved.dark)?;

    strip_internal_keys(&mut light);
    strip_internal_keys(&mut dark);

    let mut root = Value::Table(toml::map::Map::new());
    let table = root.as_table_mut().expect("root table");
    table.insert("name".into(), Value::String(name.to_string()));
    table.insert("version".into(), Value::Integer(version as i64));
    table.insert("light".into(), light);
    table.insert("dark".into(), dark);

    let body = toml::to_string_pretty(&root).expect("serialize theme TOML");
    Ok(format!(
        "# Generated by luma-theme import\n\
         # Mapping: docs/ai/next-step-theme-import.md\n\
         # Lexicon: crates/sdk/src/theme/lexicon.toml\n\
         \n\
         {body}"
    ))
}

pub fn format_binding_report(resolved: &ResolvedTheme) -> String {
    let mut lines = Vec::new();
    for report in &resolved.reports {
        lines.push(format!("[{}] {} = {} ({})", report.mode.as_str(), report.path, report.value, report.source));
    }
    lines.join("\n")
}

fn strip_internal_keys(value: &mut Value) {
    if let Some(table) = value.as_table_mut() {
        table.retain(|key, child| {
            if key.starts_with('_') {
                return false;
            }
            strip_internal_keys(child);
            !key.ends_with(".overrides") && key != "overrides"
        });
        table.remove("overrides");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::base::load_base_theme;
    use std::path::Path;

    #[test]
    fn emits_parseable_theme_for_enhance_material() {
        let css_path = crate::samples::enhance_material_css();
        let css = std::fs::read_to_string(&css_path).unwrap_or_else(|err| panic!("read {}: {err}", css_path.display()));
        let catalog = crate::catalog::parse_css_catalog(&css).unwrap();
        let lexicon =
            crate::lexicon::load_lexicon(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/src/theme/lexicon.toml"))
                .unwrap();
        let base = load_base_theme(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/src/theme/default-theme.toml"))
            .unwrap();
        let resolved = crate::resolve::resolve_theme(&catalog, &lexicon, &base.light, &base.dark).unwrap();
        let toml = emit_theme_toml("Enhance Material", 1, &base.light, &base.dark, &resolved).unwrap();
        gpui_luma::theme::LumaTheme::from_toml_str(&toml).expect("generated theme should parse");
    }

    #[test]
    fn emits_parseable_theme_for_astrovista_sample() {
        let css_path = crate::samples::astrovista_css();
        let css = std::fs::read_to_string(&css_path).unwrap_or_else(|err| panic!("read {}: {err}", css_path.display()));
        let catalog = crate::catalog::parse_css_catalog(&css).unwrap();
        let lexicon =
            crate::lexicon::load_lexicon(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/src/theme/lexicon.toml"))
                .unwrap();
        let base = load_base_theme(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdk/src/theme/default-theme.toml"))
            .unwrap();
        let resolved = crate::resolve::resolve_theme(&catalog, &lexicon, &base.light, &base.dark).unwrap();
        let toml = emit_theme_toml("Astrovista", 1, &base.light, &base.dark, &resolved).unwrap();
        gpui_luma::theme::LumaTheme::from_toml_str(&toml).expect("astrovista import should parse");
    }
}
