[package]
name = "gpui-luma-color"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false
repository.workspace = true
homepage.workspace = true

[lib]
name = "luma_color"

[features]
test-support = ["luma/test-support"]

[dependencies]
gpui.workspace = true
luma.workspace = true
anyhow.workspace = true
tiny-skia.workspace = true
palette.workspace = true
image.workspace = true
smallvec.workspace = true

[lints]
workspace = true
