[package]
name = "gpui-luma-look-shadcn-inspect"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "luma_look_shadcn_inspect"

[dependencies]
gpui.workspace = true
luma.workspace = true
luma-look-shadcn.workspace = true
anyhow.workspace = true

[dev-dependencies]
luma-shadcn-assets.workspace = true

[lints]
workspace = true
