[workspace]
resolver = "2"
members = [
  "crates/sdk",
  "crates/look-shadcn",
  "apps/gallery",
  "apps/theme-studio",
]
default-members = ["crates/sdk", "apps/gallery", "apps/theme-studio"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
anyhow = "1"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
lucide-icons = "0.575.0"
serde = "1"
tiny-skia = "0.11"
toml = "0.8"
palette = "0.7.6"

[workspace.lints.clippy]
style = { level = "allow", priority = -1 }
dbg_macro = "deny"
todo = "deny"

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package.gpui-luma]
opt-level = 2

[profile.dev.package.gpui-luma-gallery]
opt-level = 1

[profile.dev.package.gpui-luma-theme-studio]
opt-level = 1

[profile.dev.package.gpui]
opt-level = 3

[profile.dev.package.gpui_platform]
opt-level = 3

[profile.dev.package.smol]
opt-level = 3

[profile.dev.package.taffy]
opt-level = 3

[profile.dev.package.resvg]
opt-level = 3

[profile.dev.package.rustybuzz]
opt-level = 3

[profile.dev.package.ttf-parser]
opt-level = 3
