[package]
name = "luma-radix-studio"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
image.workspace = true
smallvec.workspace = true
tiny-skia.workspace = true
anyhow = { workspace = true }
gpui = { workspace = true }
gpui_platform = { workspace = true }
gpui-luma.workspace = true
gpui-luma-color.workspace = true
gpui-luma-look-radix.workspace = true
lucide-svg-static.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.18" }

[lints]
workspace = true
