[package]
name = "gpui-luma-shell-common"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true }
gpui-luma = { path = "../../../crates/sdk" }
gpui_platform = { workspace = true }
lucide-icons = { workspace = true }
gpui-luma-look-shadcn = { path = "../../../crates/look-shadcn" }
tracing = "0.1"
