[package]
name = "luma-shell-common"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true }
gpui-luma.workspace = true
gpui-luma-color.workspace = true
luma-app-common.workspace = true
gpui_platform = { workspace = true }
lucide-svg-static = { workspace = true }
gpui-luma-look-shadcn.workspace = true
tracing = "0.1"
