[package]
name = "luma-shell-common"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true }
luma = { path = "../../../crates/sdk" }
luma-fonts = { path = "../../../crates/font-assets" }
gpui_platform = { workspace = true }
lucide-svg-static = { workspace = true }
luma-look-shadcn = { path = "../../../crates/look-shadcn" }
tracing = "0.1"
