[package]
name = "gpui-luma"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
gpui.workspace = true
anyhow.workspace = true
lucide-svg-static.workspace = true
tiny-skia.workspace = true
serde = { workspace = true, features = ["derive"] }
ttf-parser = "0.25"
palette = "0.7.6"
image.workspace = true
smallvec.workspace = true
toml.workspace = true
darling = "0.23.0"
