use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use gpui::Hsla;

use super::overrides::StudioOverrides;
use crate::theme::tweakcn_dir;
use crate::studio::panels::format_hsla;

pub fn export_stylesheet(overrides: &StudioOverrides) -> anyhow::Result<PathBuf> {
    let mut light = BTreeMap::new();
    let mut dark = BTreeMap::new();

    for (token, color) in &overrides.global_color_overrides {
        let css_name = token.strip_prefix("--").unwrap_or(token.as_str()).to_string();
        let value = format_hsla(*color);
        light.insert(css_name.clone(), value.clone());
        dark.insert(css_name, value);
    }

    for (id, color_overrides) in &overrides.color_overrides {
        for (token, color) in color_overrides {
            let css_name = token.strip_prefix("--").unwrap_or(token.as_str()).to_string();
            let value = format_hsla(*color);
            light.insert(css_name.clone(), value.clone());
            dark.insert(css_name, value);
            let _ = id;
        }
    }

    let css = render_css(&light, &dark);
    let exports_dir = tweakcn_dir().join("exports");
    fs::create_dir_all(&exports_dir)?;
    let path = exports_dir.join("theme-studio-overrides.css");
    fs::write(&path, css)?;
    Ok(path)
}

fn render_css(light: &BTreeMap<String, String>, dark: &BTreeMap<String, String>) -> String {
    let mut out = String::from("/* Generated by Luma Theme Studio */\n\n:root {\n");
    for (token, value) in light {
        out.push_str(&format!("  --{token}: {value};\n"));
    }
    out.push_str("}\n\n.dark {\n");
    for (token, value) in dark {
        out.push_str(&format!("  --{token}: {value};\n"));
    }
    out.push_str("}\n");
    out
}

pub fn catalog_color_for_token(radix_theme: &gpui_luma::theme::RadixTheme, token: &str) -> Option<Hsla> {
    radix_theme.token_color(token).ok()
}

pub fn token_css_name(token: &str) -> String {
    format!("--{}", token.strip_prefix("--").unwrap_or(token))
}
