[package]
name = "gpui-luma-look-shadcn"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
gpui.workspace = true
gpui-luma = { path = "../sdk" }
gpui-luma-look-shadcn-macros = { path = "../look-shadcn-macros" }
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
palette.workspace = true

[lints]
workspace = true
