[package]
name = "luma-shell-detached"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true }
gpui-luma.workspace = true
lucide-svg-static.workspace = true
gpui_platform = { workspace = true }
gpui-luma-look-shadcn.workspace = true
luma-shell-common = { path = "../common" }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.18" }
