[package]
name = "luma-studio"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true }
luma = { path = "../../crates/sdk" }
luma-fonts = { path = "../../crates/font-assets" }
luma-look-shadcn = { path = "../../crates/look-shadcn" }
luma-look-shadcn-inspect = { path = "../../crates/look-shadcn-inspect" }
lucide-svg-static.workspace = true
gpui_platform = { workspace = true }
font-kit.workspace = true
thiserror.workspace = true
palette = { workspace = true }
serde = { workspace = true }
tracing = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.18" }
