mod account;
mod accordion;
mod chat;
mod common;

pub(crate) use common::{format_hex_color, parse_hex_color};
mod cookies;
mod dashboard;
mod navigation_sidebar;
pub(crate) mod palette;
mod payments;
mod task_list;
mod report;
mod system_preferences;
mod team;
mod tree_view;
mod typography;
mod upgrade;

pub use account::AccountPanel;
pub use accordion::AccordionPanel;
pub use chat::ChatPanel;
pub use cookies::CookiesPanel;
pub use dashboard::DashboardPanel;
pub use palette::PalettePanel;
pub use payments::PaymentsPanel;
pub use report::ReportPanel;
pub use system_preferences::SystemPreferencesPanel;
pub use team::TeamPanel;
pub use tree_view::TreeViewPanel;
pub use typography::TypographyPanel;
pub use upgrade::UpgradePanel;
