#!/usr/bin/env python3
"""Generate apps/radix-studio react-icons Icon catalog from SVG files.

Example:
  python3 scripts/generate_react_icon_catalog.py \\
    --dir apps/radix-studio/src/assets/react-icons \\
    --out apps/radix-studio/src/assets/react_icons/catalog.rs
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

RUST_KEYWORDS = {
    "as",
    "break",
    "const",
    "continue",
    "crate",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "Self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
    "async",
    "await",
    "dyn",
    "abstract",
    "become",
    "box",
    "do",
    "final",
    "macro",
    "override",
    "priv",
    "typeof",
    "unsized",
    "virtual",
    "yield",
    "try",
    "gen",
}


def to_variant(name: str) -> str:
    parts = name.split("-")
    variant = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if variant and variant[0].isdigit():
        variant = "Icon" + variant
    if variant in RUST_KEYWORDS:
        variant += "Icon"
    return variant


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    files = sorted(args.dir.glob("*.svg"))
    if not files:
        raise SystemExit(f"no svg files in {args.dir}")

    icons: list[tuple[str, str, str]] = []
    for path in files:
        name = path.stem
        variant = to_variant(name)
        text = path.read_text()
        match = re.search(r'viewBox="([^"]+)"', text)
        view_box = match.group(1) if match else "0 0 15 15"
        icons.append((variant, name, view_box))

    duplicates = [name for name, count in Counter(v for v, _, _ in icons).items() if count > 1]
    if duplicates:
        raise SystemExit(f"duplicate variants: {duplicates}")

    lines: list[str] = [
        "// @generated by scripts/generate_react_icon_catalog.py — do not edit by hand.",
        "// Radix Icons (MIT) — https://www.radix-ui.com/icons",
        "",
        "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]",
        "pub enum Icon {",
    ]
    for variant, _, _ in icons:
        lines.append(f"    {variant},")
    lines.append("}")
    lines.append("")
    lines.append("const ALL_ICONS: &[Icon] = &[")
    for variant, _, _ in icons:
        lines.append(f"    Icon::{variant},")
    lines.append("];")
    lines.append("")
    lines.append("#[allow(dead_code)]")
    lines.append(f"pub const REACT_ICON_COUNT: usize = {len(icons)};")
    lines.append("")
    lines.append("impl Icon {")
    lines.append("    pub const fn all() -> &'static [Self] {")
    lines.append("        ALL_ICONS")
    lines.append("    }")
    lines.append("")
    lines.append("    pub const fn name(self) -> &'static str {")
    lines.append("        match self {")
    for variant, name, _ in icons:
        lines.append(f'            Self::{variant} => "{name}",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    pub const fn asset_path(self) -> &'static str {")
    lines.append("        match self {")
    for variant, name, _ in icons:
        lines.append(f'            Self::{variant} => "assets/react-icons/{name}.svg",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    #[allow(dead_code)]")
    lines.append("    pub const fn view_box(self) -> &'static str {")
    lines.append("        match self {")
    for variant, _, view_box in icons:
        lines.append(f'            Self::{variant} => "{view_box}",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    pub fn from_asset_path(path: &str) -> Option<Self> {")
    lines.append("        let path = path.trim_start_matches('/');")
    lines.append("        ALL_ICONS.iter().copied().find(|icon| icon.asset_path() == path)")
    lines.append("    }")
    lines.append("")
    lines.append("    pub const fn svg_bytes(self) -> &'static [u8] {")
    lines.append("        match self {")
    for variant, name, _ in icons:
        lines.append(f'            Self::{variant} => include_bytes!("../react-icons/{name}.svg"),')
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("impl std::fmt::Display for Icon {")
    lines.append("    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
    lines.append("        formatter.write_str(self.name())")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out} ({len(icons)} icons)")


if __name__ == "__main__":
    main()
