[package]
name = "gpui-luma-theme-radix"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
gpui.workspace = true
gpui-luma = { path = "../sdk" }
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
lucide-icons.workspace = true
palette.workspace = true
