//! Metric tables derived from the same paint helpers and SDK scales used by rendering.
//! Inspection DTOs and display formatting remain in the companion crate.

pub(crate) mod helpers;
mod accordion;
pub use accordion::{AccordionMetricTable, resolve_accordion_metrics};
mod badge;
pub use badge::{BadgeMetricTable, resolve_badge_metrics};
mod button;
pub use button::{ButtonMetricTable, resolve_button_metrics};
mod card;
pub use card::{CardMetricTable, resolve_card_metrics};
mod checkbox;
pub use checkbox::{CheckboxMetricTable, resolve_checkbox_metrics};
mod context_menu;
pub use context_menu::{ContextMenuMetricTable, resolve_context_menu_metrics};
mod control_group;
pub use control_group::{ControlGroupMetricTable, resolve_control_group_metrics};
mod floating_menu;
pub use floating_menu::{FloatingMenuMetricTable, resolve_floating_menu_metrics};
mod overlay_window;
pub use overlay_window::{OverlayWindowMetricTable, resolve_overlay_window_metrics};
mod pager;
pub use pager::{PagerMetricTable, resolve_pager_metrics};
mod progress;
pub use progress::{ProgressMetricTable, resolve_progress_metrics};
mod radio;
pub use radio::{RadioButtonMetricTable, resolve_radio_button_metrics};
mod resizable_panels;
pub use resizable_panels::{ResizablePanelsMetricTable, resolve_resizable_panels_metrics};
mod scrollbar;
pub use scrollbar::{ScrollbarMetricTable, resolve_scrollbar_metrics};
mod sidebar;
pub use sidebar::{SidebarMetricTable, resolve_sidebar_metrics};
mod slider;
pub use slider::{resolve_slider_metrics_for_size, SliderMetricTable, resolve_slider_metrics};
mod split_view;
pub use split_view::{SplitViewMetricTable, resolve_split_view_metrics};
mod stepper;
pub use stepper::{StepperMetricTable, resolve_stepper_metrics};
mod switch;
pub use switch::{SwitchMetricTable, resolve_switch_metrics};
mod table;
pub use table::{TableMetricTable, resolve_table_metrics};
mod tabs;
pub use tabs::{TabsMetricTable, resolve_tabs_metrics};
mod textfield;
pub use textfield::{TextFieldMetricTable, resolve_textfield_metrics};
mod toolbar;
pub use toolbar::{ToolbarMetricTable, resolve_toolbar_metrics};
mod tree_view;
pub use tree_view::{TreeViewMetricTable, resolve_tree_view_metrics};
